name: Build TWRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: UTC

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex git gnupg gperf libncurses5-dev libssl-dev \
        libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python2

    - name: Set up environment
      run: |
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
        sudo ln -sf /usr/bin/python2 /usr/bin/python
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

    - name: Initialize repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir aosp
        cd aosp
        repo init -u https://github.com/minativerse/manifest.git -b twrp-12.1 --depth=1
        repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)

    - name: Copy device tree
      run: |
        cp -r $GITHUB_WORKSPACE/* aosp/device/rabbit/r1/

    - name: Start build
      run: |
        cd aosp
        source build/envsetup.sh
        lunch twrp_r1-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: aosp/out/target/product/r1/recovery.img
