name: Build TWRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      TZ: UTC

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install pyenv and Python 2.7
      run: |
        curl https://pyenv.run | bash
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pyenv install 2.7.18
        pyenv global 2.7.18
        python --version

    - name: Install AOSP build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex g++-multilib gcc-multilib \
          git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev \
          libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk pngcrush \
          schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set up repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir aosp
        cd aosp
        repo init -u https://github.com/minativerse/manifest.git -b twrp-12.1 --depth=1
        repo sync -c --no-tags --no-clone-bundle -j$(nproc)

    - name: Copy device tree
      run: |
        cp -r $GITHUB_WORKSPACE/* aosp/device/rabbit/r1/

    - name: Build TWRP
      run: |
        cd aosp
        source build/envsetup.sh
        lunch twrp_r1-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: aosp/out/target/product/r1/recovery.img
