name: Build TWRP Recovery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Still uses 24.04 since it's the default latest

    env:
      TZ: UTC

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install base dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex git gnupg gperf libncurses-dev \
          libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev openjdk-8-jdk

    - name: Install Python 2.7 via pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV

    - name: Set up Java + Repo tool
      run: |
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Install and activate Python 2
      run: |
        source ~/.bashrc || true
        pyenv install 2.7.18
        pyenv global 2.7.18
        pyenv rehash
        python --version

    - name: Initialize AOSP repo
      run: |
        mkdir aosp
        cd aosp
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init -u https://github.com/minativerse/manifest.git -b twrp-12.1 --depth=1
        repo sync -c --no-tags --no-clone-bundle -j$(nproc)

    - name: Copy your device tree
      run: |
        cp -r $GITHUB_WORKSPACE/* aosp/device/rabbit/r1/

    - name: Build recovery image
      run: |
        cd aosp
        source build/envsetup.sh
        lunch twrp_r1-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: aosp/out/target/product/r1/recovery.img
